version: "3.9"

services:
  postgres_db:
    container_name: postgres
    image: postgres:15.3-alpine3.18
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres-db
    ports:
      - "5432:5432"

  # redis:
  #   image: "redis:alpine"
  #   restart: always
  #   ports:
  #     - "6379:6379"

volumes:
  postgres-data:
